baseURL = "https://bawey.github.io/peripheral-memories/"
languageCode = "en-us"
title = "peripheral memories"

[outputs]
home = ["HTML", "JSON"]

[module]
theme = "hugo-theme-relearn"
[[module.imports]]
path = "github.com/McShelby/hugo-theme-relearn"

[params]
disableInlineCopyToClipBoard = true
